### PR TITLE
auto-detect content-type based on extension and apply it to the upload for S3.put/4

### PR DESCRIPTION
**Pull request by weixiyen**

### CODE REVIEW

**Comment by dmarkow** [comment]
`Plug.MIME` has a function that can take a path. So instead of

```elixir
content_type = file.file_name |> Path.extname |> String.replace(".", "") |> Plug.MIME.type
```
you should be able to do:

```elixir
content_type = Plug.MIME.path(file.file_name)
```

Additionally, using the `path/1` function will downcase the extension as well, as `type/1` requires lowercase extensions.

**Comment by blitzstudios** [comment]
Thanks @dmarkow.  I've updated the PR to use Plug.MIME.path.

**Comment by dvcrn** [comment]
Any updates on this? Especially with arc having so much support for image, it is a bit weird to see `octet-stream` as Content-Type which basically force downloads the image instead of displaying it when accessing it directly.

**Comment by stavro** [comment]
There is now preliminary support for explicitly specifying object headers via https://github.com/stavro/arc/commit/ed996ceaccf89fcf9c9b96d2dabba899cfa4f4f2.

I will consider automatically applying the header in the library in the future, but I didn't want to add Plug as a dependency yet.  The Readme and generated upload though include the Plug function necessary (though commented out) to apply the Plug MIME type.

Thanks!

**Pull request closed without merging**
