### PR TITLE
Write binary

### PR DESCRIPTION
**Pull request by stavro**
Supersedes https://github.com/stavro/arc/pull/6.

Adds:
  - [x] Ability to store a file from `%{filename: "image.png", binary: <<255, 255, 255, ...>>}` format
  - [x] Lazily saves the file to disk prior to any transformations.

### CODE REVIEW

**Comment by stavro** [comment]
@OpakAlex The format changed a little.  Rather than specifying `Arc.new(binary, filename)`, just store `%{filename: "image.png", binary: "..."}` normally.

I want to keep `Arc.File` as an internal class.

**Comment by OpakAlex** [comment]
ok @stavro. It's so simple and cool feature.

**Comment by Carrigan** [comment]
Thanks for getting this through @stavro @OpakAlex 😄

**Comment by stavro** [comment]
np I'll likely release a new version early next week - I want to get some more changes in.

Thanks!

**Pull request merged**
