### PR TITLE
Added remove object functionality

### PR DESCRIPTION
**Pull request by sashaafm**
Hello, I needed to delete the objects from S3 in my project and I saw that object deletion was on your roadmap. I gave it a try and it seems to work, I didn't do any extensive testing, just in my app. The function is called remove and I basically did the same as you did for store. The only problem seems to be that it deletes the file and the folder, instead of just the file. 

I also changed the code a bit for readibility.

### CODE REVIEW

**Comment by sashaafm** [comment]
I've been playing around with it and it seems to only work if I pass the same map used for storing the file in the same place, I guess it should only receive the URL and delete it that way.

**Comment by stavro** [comment]
Thanks @sashaafm !  I'm super busy these next couple days for obvious reasons... but I will look into this next week!

**Comment by sashaafm** [comment]
I've also been busy but I'll try to develop it further this week.

**Comment by stavro** [comment]
Accepted via https://github.com/stavro/arc/commit/a69d29202595d1586d849a7c396d6d56cc0c1519.

Thanks!

**Pull request closed without merging**
