### PR TITLE
Feature/delete temp files

### PR DESCRIPTION
**Pull request by andrewtimberlake**
Building on pull request #114 this patch tracks and cleans up the temporary files generated by transformations.

### CODE REVIEW

**Comment by stavro** [comment]
Thanks for the PR!

How does Plug handle temporary files generated during uploading?  I believe Plug cleans up files itself after the process dies.  Is there a way to piggyback off of that logic?

**Comment by andrewtimberlake** [comment]
It does. It has it’s own process management.
Briefly is a temporary file management package that uses Plugs logic

**Comment by andrewtimberlake** [comment]
Plug has no idea how the temporary file will be used so it would need to kill the file after the process. Because Arc has a controlled flow, we know when we’re done so I don’t think you need a more complicated process.

**Comment by stavro** [comment]
I'm going to close this PR because it has extra changes in it (the reducer logic). https://github.com/stavro/arc/issues/139

I've added an issue to track this - as I am still interested in handling cleanup logic.

However, I would also like to try and handle error cases / conversion failures and cleanup temporary files in a more comprehensive way.  I'll continue thinking about this.  Thanks for your input!

**Pull request closed without merging**
