### PR TITLE
Write binary

### PR DESCRIPTION
**Pull request by OpakAlex**
It's idea for write binary string as file. 

As example raw_post data in http requests.

### CODE REVIEW

**Comment by stavro** [comment]
Thanks for the PR!

Couple questions:

* Are you not using Plug?
* Can you give me a full example of how you are trying to use this?

Thanks!

**Comment by OpakAlex** [comment]
Hi man. Sorry for delay. 
i use `{:ok, data, _conn_details} = Plug.Conn.read_body(conn)`
When i need read body from request and save it.

**Comment by sean-atv** [comment]
Thanks @OpakAlex  - I will look into this soon.

**Comment by stavro** [comment]
Thanks @OpakAlex - I will look into this soon.

**Comment by princemaple** [comment]
This PR looks pretty useful.

**Comment by vitalis** [comment]
:+1: Will be a great addon to this projet

**Comment by Carrigan** [comment]
This would be really nice for saving files sent in JSON using base64. Any updates on this? I'd be happy to help get this merged.

**Comment by OpakAlex** [comment]
@Carrigan it needs merge :) i will try look into

**Comment by OpakAlex** [comment]
@Carrigan reabsed!

**Comment by stavro** [comment]
Superseded by https://github.com/stavro/arc/pull/102.

Thanks for your help!

**Pull request closed without merging**
