### PR TITLE
Allow asset_host to be set via an environment variable.

### PR DESCRIPTION
**Pull request by green-arrow**
Also brought in 'TemporaryEnv' package for doing configuration testing in test cases

### CODE REVIEW

**Comment by green-arrow** [comment]
Just as a clarification, I pulled in the `temporary_env` library because setting the `asset_host` option caused all of the tests to fail. This library seemed to provide a straightforward and easy way to test these kinds of config based functions. If there's some other way I should use and you'd like me to remove that dependency, just let me know :)

**Comment by stavro** [comment]
I like this, but I'd like to do it without `TemporaryEnv`.   If it allowed us to run the tests in an `async` way it would be worth it.

It looks like it is equivalent to using two `System.put_env` calls.  Can we try without it?

**Comment by JoshSmith** [comment]
@green-arrow bump 😄

**Comment by stavro** [comment]
Closed via https://github.com/stavro/arc/pull/124.

**Pull request closed without merging**
