### PR TITLE
update poison to ~> 1.5

### PR DESCRIPTION
**Pull request by nicholaswyoung**
I'm working on #70 and needed Poison 1.5. I need to re-run with S3 credentials to make sure it works, but I wanted to commit it in case it was helpful.

### CODE REVIEW

**Comment by sashaafm** [comment]
Hello @nicholaswyoung. I'm the maintainer/owner of the GCloudex library and I'd be willing to help you if this is accepted by Stavro. :+1:

**Comment by stavro** [comment]
Can we just mark Poison as `"~> 1"`? Does it need to be at least 1.5?

**Comment by nicholaswyoung** [comment]
@Stavro Possibly. That version was the latest that would match, though.

The ideal preference would be to work out support for the newest version (major bump), but this is a decent stopgap measure.

**Comment by nicholaswyoung** [comment]
@sashaafm I'd love the help, but GCloudex is lacking tests, and thus unsuitable for this kind of integration. Until functionality is validated, I don't feel comfortable using it for anything serious. 

I'm working on a lean, [standard API](https://github.com/nicholaswyoung/cirrus) that will work across multiple providers, if you want to contribute there. (See Cirrus.Google, which I should.he wrapping initial work on soon.)

**Comment by sashaafm** [comment]
@nicholaswyoung I've been working on tests for a couple of weeks now. They're already in master and with Travis CI :)

**Comment by sashaafm** [comment]
Sorry for the double post!

@nicholaswyoung I've just looked at your Cirrus project. It's very interesting but I'm working on something very similar (which is much more advanced than yours it seems)! I'll release a public version of it in a couple of weeks probably. Maybe we could collaborate then?

**Comment by stavro** [comment]
Sorry... I'm still confused about this.

Having a semver of `~> 1.2` will match anything between `1.2` and less than `2.0`.  If you need 1.5 in your project why do I need to change Arc's dependency?  There should be no conflict with 1.5 currently.

**Comment by nicholaswyoung** [comment]
@sashaafm When I last checked, it was lacking tests. Looking at the repo now, I see that I'm out-of-date.

> I'm working on something very similar (which is much more advanced/complete than yours so far it seems)!

Do you have a proposed API for implementing multiple providers? What I'm aiming for is similar to [Fog](https://github.com/fog/fog). I don't see that in the scope for your project. If I'm missing something, please share. We may both be heading in the same direction, but it's difficult to tell when your (unpublished) project is "much more advanced/complete." ;)

If the source code is ready to share, and we're both going after the same problem, it makes sense to collaborate.

**Comment by nicholaswyoung** [comment]
@stavro `1.5` is the latest release in the `1.x` series. `1.2`, the current dep version, is a couple of releases behind.

It makes sense to keep deps current if we can, does it not?

**Comment by nicholaswyoung** [comment]
@stavro Feel free to close if you think this isn't ideal. The main issue I'm concerned with is #70.

**Comment by stavro** [comment]
@nicholaswyoung No, it doesn't make sense to keep the dependencies pegged to the latest version.

They should remain at the widest allowable dependency windows.  By bumping Poison to `~> 1.5`, we are saying "you **must** have at least 1.5", when there is no reason why someone who is using 1.4 will have problems.

We shouldn't **force** people to upgrade all of their dependencies, because they may have some other library that only works with 1.2.

I'll take a look at #70 next.

**Comment by sashaafm** [comment]
@nicholaswyoung I'm gonna email you so we don't keep spamming this PR.

**Pull request closed without merging**
